### ISSUE TITLE
Update spotify.lua to work with awesome wm 4.0

### ISSUE THREAD

**Issue by muammar** [streetturtle/AwesomeWM#2]
In order to make the widget work again, I had to modify it as seen https://github.com/muammar/awesome/commit/9089d27c1a2a41e0c5210a88434cab6dec3d8a00.

**Comment by streetturtle** [comment]
Hi! I've created a new repo with compatible widgets: [AwesomeWM4](https://github.com/streetturtle/AwesomeWM4/). And here is [spotify.lua](https://github.com/streetturtle/AwesomeWM4/blob/master/spotify.lua).

**Comment by muammar** [comment]
@streetturtle thank you :). That's the way to go. See this: 
https://github.com/awesomeWM/awesome/issues/1419

**Comment by streetturtle** [comment]
Great! I didn't know about `widget.watch`, thanks for pointing me there!!! I'll update all my widgets and will get rid of timers.
