### ISSUE TITLE
battery.lua need to use "capacity" instead of "charge" (in some cases?)

### ISSUE THREAD

**Issue by Taddic** [streetturtle/AwesomeWM#3]
Hi,

I don't know much about the acpi and the different things under /sys/class/power_supply/BAT1/ but I figured I'd at least mention that I had to change the following lines in battery.lua to get it to work:

`local _, status, capacity, time = string.match(stdout, '(.+): (%a+), (%d%d)%%, (.+)')`
`charge = tonumber(capacity)`

Maybe it is not necessary for all systems, but at least for my system I had to do that.
Thanks for the excellent widgets, I've only tried the battery one so far but I will test the others soon enough! :)

My awesome version:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

**Comment by streetturtle** [comment]
Thanks! I'll try to generalize it a bit in near future, because I think it's also possible to have several batteries in some laptop configurations.

**Comment by Taddic** [comment]
No problem! A general one would be good, but for now maybe a comment or something somewhere in the code or in the README would suffice for now :)

**Comment by streetturtle** [comment]
I renamed the variable and now I hope it should be ok. Thanks for raising an issue :)
